---
# tasks file for ansible-gitlab-updater

  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Check and keep latest gitlab-ce version
    apt: name=gitlab-ce update_cache=yes state=latest
    become: true
    notify: 
    - Reconfigure GitLab
    - Send update email
 
  
